name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Run Linter
        run: |
            sudo apt-get install cppcheck
            cppcheck src/ --error-exitcode=1 

  build:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/cpp-app
          docker build -t $IMAGE_ID:${{ github.sha }} .
          docker push $IMAGE_ID:${{ github.sha }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull and Test
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/cpp-app
          docker pull $IMAGE_ID:${{ github.sha }}
          docker run --rm $IMAGE_ID:${{ github.sha }} ./my_test
